Experimental
sandkastenboys/memologe pull request #12
Opened 2019-07-26 20:29 UTC by SpartanerSpaten

added logging, a lot of bug fixes

2019-07-26 20:30 UTC, pep8speaks commented
Hello @SpartanerSpaten! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:















* In the file [`app/objects.py`](https://github.com/sandkastenboys/memologe/blob/d3536b645afedfc2090affe2154ac60025087523/app/objects.py):

> [Line 43:9](https://github.com/sandkastenboys/memologe/blob/d3536b645afedfc2090affe2154ac60025087523/app/objects.py#L43): [F841](https://duckduckgo.com/?q=pep8%20F841) local variable 'e' is assigned to but never used
> [Line 52:13](https://github.com/sandkastenboys/memologe/blob/d3536b645afedfc2090affe2154ac60025087523/app/objects.py#L52): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'

2019-07-27 01:17 UTC, SuperSandro2000 requested changes

2019-07-27 01:17 UTC, SuperSandro2000 commented on app/func/essentials.py
> +    author: User = database_handler.session.query(User).filter_by(username=author_name, platform=platform).first()
Types?

2019-07-27 01:22 UTC, SuperSandro2000 reviewed
Hier hat dein Formatierer kacke gebaut.

2019-07-27 01:22 UTC, SuperSandro2000 commented on app/handler/Telegram.py
> +        message.reply_text(str(e))
Ich würde nicht den trace als Fehler zurück schicken.

2019-07-27 01:22 UTC, SuperSandro2000 commented on app/objects.py
> +
\n zu viel

2019-07-27 01:22 UTC, SuperSandro2000 commented on app/handler/Telegram.py
> +  #  conv_handler = ConversationHandler(
Commite keinen auskommentierten Code

2019-07-27 01:22 UTC, SuperSandro2000 commented on app/objects.py
> +            except:  # FIXME put correct exception
FIXME

2019-07-27 01:22 UTC, SuperSandro2000 commented on app/handler/Telegram.py
> +    rate_meme(meme_id, -1, username, 1)
Das ist ja ziemlich häufig. Du solltest wohl eine Funktion daraus stricken.

2019-07-28 11:27 UTC, SpartanerSpaten commented on app/handler/Telegram.py
> +    rate_meme(meme_id, -1, username, 1)
done

2019-07-28 11:27 UTC, SpartanerSpaten commented on app/objects.py
> +
done

2019-07-28 11:28 UTC, SpartanerSpaten commented on app/handler/Telegram.py
> +        message.reply_text(str(e))
outdated done

2019-07-28 11:29 UTC, SpartanerSpaten commented on app/func/essentials.py
> +    author: User = database_handler.session.query(User).filter_by(username=author_name, platform=platform).first()
done

2019-07-28 19:50 UTC, SuperSandro2000 commented
CI ist noch rot.

2019-07-28 20:07 UTC, SpartanerSpaten commented
Ist das weil Flake mit 1 terminated ?

2019-07-28 20:24 UTC, SpartanerSpaten commented
Alles was Flake jetzt noch hatte sollte behoben sein

2019-07-28 20:35 UTC, SpartanerSpaten commented
dein Approve ...

2019-07-29 07:24 UTC, SuperSandro2000 requested changes

2019-07-29 07:24 UTC, SuperSandro2000 commented on app/func/search.py
> +
Das ist unnötig

2019-07-29 07:24 UTC, SuperSandro2000 commented on app/handler/Telegram.py
> +
Unnötig

2019-07-29 07:24 UTC, SuperSandro2000 commented on app/objects.py
> +            logger.critical("Can not reconnect to database", exc_info=True)
Schmeißt du hier den trace weg?

2019-07-29 07:24 UTC, SuperSandro2000 commented on app/handler/Discord.py
> +                logger.error(error, exc_info=True)
Gibt sowas dann 2 traces hintereinander?

2019-07-29 19:42 UTC, SpartanerSpaten commented on app/handler/Discord.py
> +                logger.error(error, exc_info=True)
kA ich würde aber sagen nein

2019-07-29 21:09 UTC, SuperSandro2000 commented on app/handler/Discord.py
> +                logger.error(error, exc_info=True)
Wäre sonst sehr verwirrend.

2019-07-30 10:04 UTC, merged